name: Code Quality

on:
  pull_request:
    branches: [ main, development ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: mbstring, xml, ctype, json
        tools: composer

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install Composer dependencies
      run: composer install --no-progress --no-interaction --prefer-dist --optimize-autoloader

    - name: Install NPM dependencies
      run: npm install

    - name: Run PHP CodeSniffer
      run: composer run check

    - name: Run CSS Linting
      run: npm run lint:css

    - name: Run JavaScript Linting
      run: npm run lint:js

    - name: Run PHP Linting
      run: npm run lint:php

    - name: Check PHP compatibility
      run: ./vendor/bin/phpcs --standard=PHPCompatibility --runtime-set testVersion 7.4- *.php
