name: Code Linting

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run JavaScript linting
      run: npm run lint:js

    - name: Run CSS linting  
      run: npm run lint:css

    - name: Run complete lint check
      run: npm run lint:check